googleapis/java-firestore

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
Methods in CollectionReference, DocumentReference and UpdateBuilder need to keep their `Map<String, Object>` variants to preserve binary compatibility with any project that was compiled against a version of google-cloud-firestore prior to this change.
Original feature commit: 180f5a96
> chore: partial revert of 180f5a96 to restore methods for binary compatibility

- google-cloud-firestore/pom.xml
- grpc-google-cloud-firestore-admin-v1/pom.xml
- grpc-google-cloud-firestore-v1/pom.xml
- grpc-google-cloud-firestore-v1beta1/pom.xml
> build: exclude animal-sniffer-annotations from grpc-api

- pom.xml
With the recent bump to auto-value-annotations 1.7 IntelliJ is not longer
able to build the project due to a NoClassDefFoundError.
Here we manually pull in auto-service-annotations so that it is part of the
processor path because auto-value has it set to provided scope.
This dependency is needed due to the retention change in
https://github.com/google/auto/commit/628df548685b4fc0f2a9af856f97cc2a68da246b
where the RetentionPolicy changed from SOURCE to CLASS.
Due to the RetentionPolicy change to CLASS we must have the
annotations available on the processor path otherwise the following
will error will be thrown. (This is a particular problem with the
annotation processor configuration in IntelliJ)
Error:java: java.lang.NoClassDefFoundError: com/google/auto/service/AutoService …
> build: update annotationProcessorPaths to include auto-service-annotations

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreException.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
Right now if a transaction fails due to a precondition failure (which are retried, which is another bug) for example trying to update a document that doesn't exist you get a bad error message of "too many retries". Ideally retry is smarter, but this is a easy change that propagates the underlying error up to the ApiFuture result.
/cc @schmidt-sebastian @BenWhitehead
> fix: add cause to transaction errors on transaction commit

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
queryWatch has been flaky because several things are happening in the
single event stream. This fix splits up the different scenarios being
tested into their own respective tests and updates the assertions to be
more specific to the scenario as well as handling the semantics of the
backend better.
> fix: deflake-ify ITSystemTest#queryWatch

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
Fixes #43 (it's a good idea to open an issue first for context and/or discussion)
> feat: add new Firestore.runAsyncTransaction

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
"Client" interfaces make guarantees around compatibility for users
direct usage, however no guarantee is made for anyone implementing
the "client" interface themselves. This change adds the annotation
intended to convey this guarantee at the code level and in javadocs
that should have been here all along.
> fix: add missing @InternalExtensionOnly annotation to com.google.cloud.firestore.Firestore

- google-cloud-firestore/clirr-ignored-differences.xml
Fixes the broken build from new methods added in #103
> chore: add clirr-ignored-differences.xml for new runAsyncTransaction methods added to Firestore

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
> fix: add support for updating an individual field with pojo in all update method

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
> feat: use SecureRandom instead of Random to reduce the chance of auto-id collisions

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/MapperTest.java
> feat: add CustomClassMapper#convertBigDecimal for Deserializer

- CONTRIBUTING.md
In a game of telephone, Sebastian told me that you told him this was a command you can run to lint the java-firestore repo. Adding to `CONTRIBUTING.md` for future contributors.
> docs: update README to include code formatting

- .gitignore
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/993).
> fix: support array of references for IN queries

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Checking for null in the `before()` block doesn't surface the error, since the `after()` call will still run even with a thrown exception, smothering the error.
> fix: catch null Firestore in system tests

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
Fields appear in `whereIn` queries are used as implicit orderBys. This is wrong because `In` should be an equality filter.
This change brings Java SDK in line with Node in terms of how equality/inequality filters are determined.
> fix: Fields used in whereIn should be equality filters

- google-cloud-firestore/pom.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentTransform.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/949). Also added additional system test [port](https://github.com/googleapis/nodejs-firestore/pull/1035/files#diff-6b8febc8d51ea01205628091b3611eacR422) as well. 
Conformance tests are passing locally against the custom [branch] of modified conformance tests (https://github.com/googleapis/java-conformance-tests/tree/bump/2020-05-12_141750) in `googleapis/java-conformance-test`. According to @BenWhitehead, once this PR is LGTM'd, we will:
1. Merge the conformance test [PR](https://github.com/googleapis/conformance-tests/pull/34) into `conformance-tests`.
2. Create new release of `java-conformance-tests`. 
3. Update `java-firestore` to the new release.
4. Rebuild this PR and ensure everything passes before merging.
> fix: replace usages of transform proto with update_transform

- pom.xml
This is expected to not build since it's pointing at a snapshot of shared-config.
But it is illustrative of what the usage of the auto-value profile(s) from shared config look like.
Related to: https://github.com/googleapis/java-shared-config/pull/136
> build: update maven config to use autovalue from shared-config

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/RateLimiter.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/RateLimiterTest.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/1021).
> fix: add RateLimiter

- .github/CODEOWNERS
- .repo-metadata.json
- CONTRIBUTING.md
- synth.metadata
CODEOWNERS is now managed by templates and we can configure the default team in the .repo-metadata.json file.
> chore: update CODEOWNERS, CONTRIBUTING from templates

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BatchWriteResult.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Porting integration tests from [node](https://github.com/googleapis/nodejs-firestore/pull/1117).
After running into a few BE contention errors during testing, I also added the error message to `BatchWriteResult`, since backend errors were not being returned in a useful manner.
> fix: add BulkWriter system tests + pass BE error messages

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
> feat: add support for fieldmask to document reference

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldPath.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreRpcContext.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/QueryDocumentSnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/ResourcePath.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
This PR adds an API to serialize and deserialize Queries to and from RunQueryRequests. The new API endpoints are `Query.toProto` and `Query.fromProto`.
> feat: add API to serialize Queries to Proto

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BasePath.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldPath.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
> fix: add support for deleting nested fields that contain periods

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
Fixes https://github.com/firebase/firebase-admin-java/issues/452
> fix: use test credentials when connecting to the Emulator from Admin SDK

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreRpcContext.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
> chore!: remove deprecated FirestoreOptions#setTimestampsInSnapshotsEnabled

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
* Add timeout rule to fail a test if it runs for longer than 500ms. (This is helpful because there appear to be some sort of hang in a few of the tests.)
> test: add junit timeout rule to BulkWriterTest

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/QueryPartition.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/FirestoreRpc.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
This changes Firestore.collectionGroup() to return a new CollectionGroup class. CollectionGroup then gets a new getPartitions() API, which is usable as long as the Query hasn't been customized (which would turn CollectionGroup into a Query).
> feat!: add support for the Query Partition API

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BatchWriteResult.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
- pom.xml
Porting over from [node](https://github.com/googleapis/nodejs-firestore/pull/1243).
> fix: add retry on ABORTED errors

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
> chore: cleanup of leftover remnants of Timestamps in Snapshots

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
This change allows users who want to try to manually configured FirestoreOptions for an emulator to be able to leverage the credentials we use when boostrapping via environment variable.
* Rename FakeCredentials to EmulatorCredentials
* Make EmulatorCredentials static
* Move from inner class of FirestoreOptions.Builder to inner class of FirestoreOptions
Related to #190
> fix: refactor FakeCredentials

- pom.xml
Now that shared-dependencies v0.8.6 has been released and is used in pom.xml we no longer need the manual version pull for api-commons.
> chore(build): cleanup manually set api-commons version

- google-cloud-firestore/pom.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
* Add new typesafe builders for read-only `TransactionOptions.readOnlyOptionsBuilder` and read-write `TransactionOptions.readWriteOptionsBuilder` transactions in TransactionOptions
* These new builders ensure only those parameters relevant to the respective type of transaction are available
* Deprecate existing `TransactionOptions.create(...)` methods in favor of the new builders
* Deprecate existing and annotate @InternalApi `TransactionOptions.getNumberOfAttempts`
* Update Transaction and TransactionRunner to use TransactionOptions directly
> feat: add support for read-only transactions in TransactionOptions

- google-cloud-firestore-admin/pom.xml
- google-cloud-firestore/pom.xml
Removed /master/tree from POM file links to match style of other Google Cloud libraries
> chore: fix URLs found in POM files changed to match typical repository URL format

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
> fix: add support to deserialize to custom Lists and Maps

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
See for initial discussion: #319
Fixes #319, #210.
Relates to #190.
Similar issues in other SDKs: https://github.com/googleapis/google-cloud-go/issues/1978, https://github.com/firebase/firebase-admin-node/issues/776.
> feat: add method to set emulator host programmatically (#319)

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/1292)
> feat: add support for != and NOT_IN queries

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TraceUtil.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
> feat: add opencensus tracing support

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BatchWriteResult.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/1298).
> fix: bulkWriter: writing to the same doc doesn't create a new batch

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/RateLimiter.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/RateLimiterTest.java
Porting [throttling options](https://github.com/googleapis/nodejs-firestore/pull/1305) and [rate limiter test fix](https://github.com/googleapis/nodejs-firestore/pull/1307) from node.
> feat: add max/min throttling options to BulkWriterOptions

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
This restarts query streams that fail with a retryable error based on the last document received.
Port of https://github.com/googleapis/nodejs-firestore/pull/1116
> fix: retry Query streams

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Adding a manual verification for the partition count since we are requesting one less partition from the backend, which creates a confusing error message if the user uses a negative (or zero) partition count.
> fix: verify page count before invoking QueryPartition RPC

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
The backend orders every query implicitly by document name, but if a cursor is specified, the order constraint has to be made explicit. This makes the Partition API harder to use, since the user needs to manually "prepend" and orderBy before they can use the cursor values in a QueryPartition.
This PR adds an implicit orderBy if the only cursor value is a DocumentReference. This is based on existing logic for DocumentSnapshots.
Port of https://github.com/googleapis/nodejs-firestore/pull/1328
> feat: add implicit ordering for startAt(DocumentReference) calls

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
Port of https://github.com/googleapis/nodejs-firestore/pull/1347
Once a transaction expires, the backend returns INVALID_ARGUMENT. While INVALID_ARGUMENT is not generally retryable, we want to retry INVALID_ARGUMENT for expired transactions only. We should only retry if the error message contains "transaction has expired" and if we have previously received a transaction ID.
This PR aligns the Java SDK a little more with the Node SDK:
- Rollback RPC is the first step in transaction processing, which allows it to use the same `ApiFutures.catchingAsync` for all error handling.
There are some test updates:
- I had to drop the Map from the ResponseStubber since one of the tests I created has two Rollback RPCs, which ended up overwriting each other in the Map implementation (based on key …
> fix: retry transactions that fail with expired transaction IDs

- samples/snippets/src/main/java/com/example/firestore/Quickstart.java
- samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
- samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
- samples/snippets/src/main/java/com/example/firestore/snippets/References.java
- samples/snippets/src/test/java/com/example/firestore/QuickstartIT.java
- samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
> fix(build): sample checkstyle violations

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
PR to release bundles. Will merge when we decide to release.
> feat: Release bundles

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterException.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Add `@BetaApi` annotation to BulkWriter, along with making the `BulkWriterOptions` class public. Also refactored the executor into the options object, to better mirror the `Transaction` API.
> fix: add @BetaApi, make BulkWriter public, and refactor Executor

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentTransform.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreException.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
* Expose each factory method at @BetaApi level ensuring no guarantee about api surface
* Expose getStatus() at @BetaApi up from package private @InternalApi
> chore: make FirestoreException factory methods public to allow construction for testing

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Add new method to `CollectionGroup` allowing `getPartitions` to return a `Future<List<QueryPartition>>`. This new method behaves similar to the `CollectionGroup#getPartitions(long, ApiStreamObserver<QueryPartition>)` providing a Future centric api.
> feat: add CollectionGroup#getPartitions(long)

- google-cloud-firestore-bom/pom.xml
- pom.xml
Fixes broken builds from #369 visible in https://github.com/googleapis/java-firestore/pull/369/checks?check_run_id=1710823233
> build: fix version tags to use correct values

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
Fixes https://github.com/googleapis/java-firestore/issues/491
> fix: don't throw NPE in DocumentSnapshot.getDate() when value is missing

- samples/snippets/src/main/java/com/example/firestore/Quickstart.java
- samples/snippets/src/main/java/com/example/firestore/snippets/ListenDataSnippets.java
- samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
- samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
- samples/snippets/src/main/java/com/example/firestore/snippets/RetrieveDataSnippets.java
- samples/snippets/src/test/java/com/example/firestore/BaseIntegrationTest.java
- samples/snippets/src/test/java/com/example/firestore/QuickstartIT.java
- samples/snippets/src/test/java/com/example/firestore/snippets/ListenDataSnippetsIT.java
- samples/snippets/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java
- samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
- samples/snippets/src/test/java/com/example/firestore/snippets/RetrieveDataSnippetsIT.java
> fix(samples): close firestore instance in test

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
> fix: block close() on the termination of all RPC channels

- google-cloud-firestore/pom.xml
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/MapperTest.java
Signed-off-by: Abhijeet Shukla <abhijeetshuklaoist@gmail.com>
Fixes #506 ☕️
> Removed Jackson dependency

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
It appears that the message from the server has changed, causing one of the assertion checks to fail.
This commit updates the assertion to fix the test failure.
Fixes #588
> test: Update assertion in failing test: ITSystemTest.readOnlyTransaction_failureWhenAttemptReadOlderThan60Seconds

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkCommitBatch.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOperation.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Combination of [1](https://github.com/googleapis/nodejs-firestore/pull/1447) and [2](https://github.com/googleapis/nodejs-firestore/pull/1451) from node.
> feat: add backoff to BulkWriter

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/1470)
> feat: add buffering layer to BulkWriter

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
Found this bug while adding recursive delete tests. I tried to think of a way to add a unit test to check for this, but I couldn't think of an easy test since `scheduleCurrentBatchLocked()` automatically returns if there are no mutations.
However, not having this check was causing the `startAfter()` recursive delete test to flake, so that's some indirect coverage 😨
> fix: add flush check in BulkWriter.sendBatchLocked() callback

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/RecursiveDelete.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/ResourcePath.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Porting from node. Merging to a feature branch until it's good to release.
Several PRs are contained in here: [1](https://github.com/googleapis/nodejs-firestore/pull/1453), [2](https://github.com/googleapis/nodejs-firestore/pull/1412), [3](https://github.com/googleapis/nodejs-firestore/pull/1427).
> feat: add recursiveDelete() to Firestore

- pom.xml
Works with docfx profile from shared-config. Adding custom config to exclude package-info file creating issues on generation. Tested with trigger off this commit and generation is working as intended
> chore: cloud-rad doc generation

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Order.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/PartitionQuery.java
The Partition RPC does not guarantee that results are returned in order, which means we have to sort the partitions before we can use them as cursors.
Port of https://github.com/googleapis/nodejs-firestore/pull/1521
We don't have unit tests for PartitionQueries as we never figured out how to mock paged respones.
> fix: return results from getPartitions() in order

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
It seems like the error message for this has been updated.
> test(fix): remove assertion on error message for reads older than 60 seconds

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Fixes #667.
The callback `onFailure` is only triggered if the ApiFuture contains the exception. When a runtime exception is thrown neither the `onFailure` nor `onSuccess` handler is called, leading the ApiFuture to hang and never complete.
The fix adds a `catchingAsync()` around `updateCallback` to guard against thrown exceptions. Added a system test for redundancy, but I can remove it. Both tests fail (never complete) when run against master.
> fix: handle thrown exceptions in runAsyncTransaction callback

- google-cloud-firestore/clirr-ignored-differences.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/FirestoreRpc.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITShutdownTest.java
This adds a `shutdown` and a `shutdownNow` message. Unfortunately, it probably requires a major version bump since the method is added to the main interface (did we make exceptions before?).
> feat: add shutdown() and shutdownNow()

- google-cloud-firestore-bom/pom.xml
All java client libraries inherit the distributionManagement section form shared-config. To prevent individual pom files from overriding the shared-config version of distributionManagement, it is being removed.
> chore: remove distributionManagement section

- samples/snippets/src/main/java/com/example/firestore/Quickstart.java
This comes as part of an effort to consolidate the [`firestore_setup_client_create`](https://cloud.google.com/firestore/docs/samples/firestore-setup-client-create) and [`firestore_setup_client_create_with_project_id`](https://cloud.google.com/firestore/docs/samples/firestore-setup-client-create-with-project-id) regions.
> docs: began merging variant client samples

- pom.xml
Including javadoc plugin needed for googleapis.dev and cloud rad generation to work
test with `mvn clean site` or `mvn clean site -P docFX`
Fixes #724
> chore: fix doc generation

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreRpcContext.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/PartitionQuery.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/WatchTest.java
The Watch code called "onCompleted" to close the stream - but that did not actually do anything. This PR migrates our streaming GAPIC APIs to ClientStream (which is not deprecated) and then calls "close()" instead.
Fixes: https://github.com/googleapis/java-firestore/issues/822
> fix: close the Watch stream when we receive an error

- samples/native-image-sample/README.md
- samples/native-image-sample/pom.xml
- samples/native-image-sample/src/main/java/com/example/firestore/NativeImageFirestoreSample.java
- samples/native-image-sample/src/main/java/com/example/firestore/Person.java
- samples/native-image-sample/src/main/resources/META-INF/native-image/reflect-config.json
- samples/native-image-sample/src/test/java/com/example/firestore/ITNativeImageFirestoreSample.java
- samples/pom.xml
This PR copies over the Firestore sample, Setup Instructions and README for native image support from [GoogleCloudPlatform/native-image-support-java](https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/firestore-sample). It  also adds an integration test that can be run as a native image.
Calling `mvn package -Pnative -DskipTests` builds the native image for the application and calling `mvn test -Pnative` runs the test as a native image. 
For more information: https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration
> docs(sample): Add sample for native image support in Firestore

- google-cloud-firestore/src/main/resources/META-INF/native-image/reflect-config.json
Currently running `mvn test -Pnative` is resulting in the following errors:
```
JUnit Vintage:ITSystemTest:setDocumentWithFloat
MethodSource [className = 'com.google.cloud.firestore.it.ITSystemTest', methodName = 'setDocumentWithFloat', methodParameterTypes = '']
=> java.lang.RuntimeException: No properties to serialize found on class com.google.cloud.firestore.LocalFirestoreHelper$SingleField
com.google.cloud.firestore.CustomClassMapper$BeanMapper.<init>(CustomClassMapper.java:765)
com.google.cloud.firestore.CustomClassMapper.loadOrCreateBeanMapperForClass(CustomClassMapper.java:410)
com.google.cloud.firestore.CustomClassMapper.convertBean(CustomClassMapper.java:591)
com.google.cloud.firestore.CustomClassMapper.deserializeToClass(CustomClassMapper.java:256) …
```
> fix(java): add reflection configuration for native image tests

- README.md
- samples/native-image-sample/pom.xml
This should fix the Native Image sample which is failing with the following error:
> docs(sample): Use Java 8 for native image sample

- .kokoro/presubmit/graalvm-native.cfg
- README.md
- google-cloud-firestore/src/main/resources/META-INF/native-image/reflect-config.json
- owlbot.py
This PR makes the Kokoro presubmit setup for Graal tests consistent with that of the standard Java integration tests. 
This should help address the following failure in the Kokoro GraalVM presubmit job:
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.
```
cc @meltsufin
> fix(java): fix native image Kokoro test setup

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
Add logical termination for RunQueryResponse.
When the SDK side receives either halfClose or RunQueryResponse.done set to true, the SDK will return user requested documents.
> feat: add logical termination for RunQueryResponse

- google-cloud-firestore/pom.xml
Fixing similar issues as https://github.com/googleapis/java-pubsub/issues/1239.
In this case, declaring gson as test causes the flatten-maven-plugin to exclude gson from other dependency declarations.
> fix: declare gson as runtime rather than test

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuerySnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/FirestoreRpc.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/AggregateQuerySnapshotTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/AggregateQueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITAggregateQueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryCountTest.java
Initial implementation of server-side query result set counting.
This initial implementation is still missing some work, which will be done in follow-up PRs:
- transaction support (i.e. `Transaction.getCount()`)
- tracing support (i.e. `Tracing.getTracer()`)
> feat: Query.count() implementation, part 1

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/ITQueryCountTest.java
The test aggregateQueryInATransactionShouldRespectReadTime fails when run against the Firestore emulator due to a known issue: b/220918135 (When creating a new read-only or read-write transaction, the Firestore emulator creates the transaction at the current time regardless of the user's specified TransactionsOptions. In the case of read-only transaction, if the user specifies the read_time, that will not be honoured. If the user specifies a retry_transaction, that will not be honored).
Instead of letting the test fail, this PR has it be skipped with an appropriate error message.
> test: Skip aggregateQueryInATransactionShouldRespectReadTime when run against the emulator

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuery.java
This is a follow-up from a comment in a previous PR: https://github.com/googleapis/java-firestore/pull/1033#discussion_r976892058
> docs: AggregateQuery.java: describe why we ignore subsequent responses

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryCountTest.java
This PR reverts https://github.com/googleapis/java-firestore/pull/1044, which disabled the test `aggregateQueryInATransactionShouldRespectReadTime` because of a known issue: b/220918135 (When creating a new read-only or read-write transaction, the Firestore emulator creates the transaction at the current time regardless of the user's specified TransactionsOptions. In the case of read-only transaction, if the user specifies the read_time, that will not be honoured. If the user specifies a retry_transaction, that will not be honored).
The issue has been confirmed fixed in `cloud-firestore-emulator-v1.15.1.jar`, so skipping the test is no longer required. This PR re-enables the test when run against he Firestore Emulator.
> test: Re-enable aggregateQueryInATransactionShouldRespectReadTime when run against the emulator

- samples/snippets/src/test/java/com/example/firestore/beam/ExampleFirestoreWriteReadTest.java
The `ExampleFirestoreWriteReadTest.tearDown()` method assumes that the static variables `firestore` and `collectionId` are not null; however, if `setUp()` failed with an exception, then these variables are null. In such a case, `tearDown()` throws a `NullPointerException`. This NPE is just added noise that distracts from the real issue, that `setUp()` failed. This PR fixes this noisy NPE by simply performing a null check before using these static variables.
> test: Fix distracting NPE from ExampleFirestoreWriteReadTest.tearDown()

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryCountTest.java
When `AggregateQuery` was added by #1033 it failed to implement any "retry" logic. This PR adds in that retry logic, based heavily on the pre-existing retry logic from the `Query` class.
> feat: Add retry logic to COUNT queries

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryWatchTest.java
This PR fixes a bug where adding startAt(), startAfter(), endAt(), or endBefore() to a limitToLast query would cause the result set to be either zero or one documents in size, regardless of the limit. The root cause was a bug in the inversion logic of these conditions when the query was sent over the wire.
Fixes #1068
> fix: Fix limitToLast queries with cursors

- .github/.OwlBot.yaml
With the field, this repository should receive the "owl-bot-update-lock" pull requests. This is a follow-up for https://github.com/googleapis/java-firestore/pull/1078#issuecomment-1290935777.
> chore: owlbot-java configuration

- README.md
- samples/snippets/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
- samples/snippets/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java
As part of feature work for snapshot reads, add examples for the documentation.
Fixes #1002  ☕️
> samples: Add example snippets for stale reads

- pom.xml
Fixes #1342 
This is an idea to fix the problem. Creating another PR to upgrade Mockito. => #1344 turned out many errors. So I'm for this #1343.
> ci: Java 17 profile to run tests with old Mockito

- pom.xml
A more permanent fix was done in [#1345](https://github.com/googleapis/java-firestore/pull/1345)
So we can revert [#1343](https://github.com/googleapis/java-firestore/pull/1343)
> Revert "ci: Java 17 profile to run tests with old Mockito (#1343)"

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreStub.java
Remove 'x-goog-request-params' from headers, and fallback on `google-cloud-resource-prefix` instead.
> fix: Remove  'x-goog-request-params' header from GRPC requests due to incorrect format.

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
Passing in DocumentReference into cursor without adding orderBy clause on document key field works right at the moment. But this is not an intended behaviour and will be fixed soon. Adding a warning message before we release the fix.
> Add warning message when passing DcoumentReference in cursor

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
Patch on this fix:https://github.com/googleapis/java-firestore/pull/1397 
The warning message should display if user is passing in a single DocumentReference into a cursor, but didn't add an orderBy clause.
> Check orderBy clause when display warning for DocumentReference in cursor

- README.md
- google-cloud-firestore/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-firestore/reflect-config.json
For tests failing in https://github.com/googleapis/java-firestore/pull/1417.
Stacktrace:
```
JUnit Vintage:ITSystemTest:testBuildingBundleWhenDocumentDoesNotExist
MethodSource [className = 'com.google.cloud.firestore.it.ITSystemTest', methodName = 'testBuildingBundleWhenDocumentDoesNotExist', methodParameterTypes = '']
=> java.lang.IllegalStateException: Generated message class "com.google.firestore.bundle.BundleElement" missing method "getMetadata".
com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1998)
com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2347) …
```
> fix: add reflections configs for generated firestore classes

- google-cloud-firestore/pom.xml
- pom.xml
Renovate bot has failing PR that should be fixed by removing this unused dependency.
https://github.com/googleapis/java-firestore/pull/1428
> deps: Remove unused dependency that is blocking PR 1428

- google-cloud-firestore-admin/pom.xml
- google-cloud-firestore/pom.xml
- grpc-google-cloud-firestore-admin-v1/pom.xml
- grpc-google-cloud-firestore-v1/pom.xml
- pom.xml
The maven-javadoc-plugin version is defined in the shared config pom.xml.
https://github.com/googleapis/java-shared-config/blob/778a547a09de71dbf9e5a42b155f12d15c319864/pom.xml#L472
The removal of the 4 lines corresponds to the lines touched by the recent RenovateBot:
https://github.com/googleapis/java-firestore/pull/1427
Parent issue: https://github.com/googleapis/java-shared-config/issues/673
> build: do not declare javadoc plugin version

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/TransactionRunner.java
There is no functional change, just fewer objects wrapping functions.
> refactor: Reduce code bloat by using lambdas.

- README.md
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/RecursiveDeleteTest.java
See [this](https://b.corp.google.com/issues/233747036#comment6) for more context
> test: Increase timeout for RecursiveDeleteTests

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
Fixes https://github.com/googleapis/java-firestore/issues/1183
> fix: Better error message when Transaction/WriteBatch is modified after commit.

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
Internal tracking: b/318686162
A rollback is meant to be best effort. If the transaction has already expired, it is possible for the rollback to fail due to transaction no longer existing in Firestore. The retry logic will use attempts to rollback, and in the case where transaction no longer exists, all attempts to be exhausted attempted to rollback transaction.
This PR makes the rollback best effort, simply logging any rollback error and continuing.
> fix: Make rollback best effort.

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldMask.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
Optimization does 2 things:
1. Avoid creating intermediary collections. Simply create a TreeSet that is used in FieldMask constructor.
2. Instead of adding FieldPaths to an intermediary collection and then removing them afterwards, simply filter FieldPaths as part of TreeSet creation.
> refactor: Optimize FieldMask instantiation

- google-cloud-firestore/pom.xml
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Precondition.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
This addresses a bug reported against the .NET SDK (https://github.com/googleapis/google-cloud-dotnet/issues/11361) but applies to all SDKs. The conformance test was updated accordingly in https://github.com/googleapis/conformance-tests/pull/82 and https://github.com/googleapis/conformance-tests/pull/84.
This PR is a port of https://github.com/googleapis/nodejs-firestore/pull/1985.
Googlers see b/321064909 for more information.
> fix: Allow an explicit MustExist precondition for update

- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
- google-cloud-firestore-bom/pom.xml
- pom.xml
Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central.
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290
> chore: use sdk-platform-java-config to consolidate build config

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpcTest.java
Internal tracking: b/283455016
The retry settings found in `FirestoreStubSettings` are being overridden, whether or not the customer provides an override. To prevent this, we conditionally override based on whether customer has provided retry settings.
In addition, default for `maxAttempts` is omitted from automatically generated in code. There is a link to issue in code. Until this issue is resolved, we will need to override `maxAttempts`, but everything else should be according to build-in config.
Also, the new streaming endpoint AggregateQuery never had the retry config applied. That is also fixed in this PR.
> fix: Only override built-in retry settings when the customer provides them.

- google-cloud-firestore/pom.xml
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITE2ETracingTest.java
test: Basic test-case to ensure to verify end-to-end tracing is working using Otel SDK, Cloud Trace Exporter and Cloud Trace v1 API.
Fixes #1604 ☕️
> test: Adding first e2e client-tracing test w/ Custom Root Span

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BeanMapper.java
This is a fix for the rebase of this branch onto main.
In [a separate PR](https://github.com/googleapis/java-firestore/pull/1586), I have changed the method `CustomClassMapper.applyFieldAnnotations`, which is being moved in the record branch to class `BeanMapper`.
This PR applies the change to that method, which was lost in the rebase, in its new location.
> Fix Instant-record merge

- .github/workflows/ci.yaml
The Java 8 unit test special setup ("compile in Java 17 and run tests in Java 8") was introduced by the template change for java-spanner https://github.com/googleapis/java-spanner/pull/1870. This java-firestore repository does not need the special setup.
@milaGGL
> ci: simplify java 8 unit tests

- google-cloud-firestore/clirr-ignored-differences.xml
A feature branch that marks CustomClassMapper public has been reverted, and this is causing clirr check to fail.
> Fix: fix clirr check failure

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionGroup.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentChange.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/GenericQuerySnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/SilenceableBidiStream.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/StreamableQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/VectorQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/VectorQueryOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/VectorValue.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
Add `toString` methods to several classes that are logged.
Change logging level from `INFO` to `FINE` in a few places that seem to spam.
Fixes #1891 ☕️
> feat: Improve Logging

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreRpcContext.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/StreamableQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/telemetry/CompositeApiTracer.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/telemetry/EnabledTraceUtil.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryCountTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/telemetry/EnabledTraceUtilTest.java
This PR introduces `java.time` alternatives to existing `org.threeten.bp.*` methods, as well as switching internal variables (if any) to `java.time`
The main constraint is to keep the changes backwards compatible, so for each existing threeten method "`method1(org.threeten.bp.Duration)`" we will add an alternative with a _Duration_ (or _Timestamp_ when applicable) suffix: "`method1Duration(java.time.Duration)`".
For most cases, the implementation will be held in the `java.time` method and the old threeten method will just delegate the call to it. However, for the case of abstract classes, the implementation will be kept in the threeten method to avoid breaking changes (i.e. users that already overloaded the method in their user code).
> feat: introduce `java.time` variables and methods

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
Should fix: https://github.com/googleapis/java-firestore/issues/1772
> fix: BulkWriter flush logic

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Order.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/OrderTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryTest.java
SDK sorts cross-type numbers differently than the backend in some edge cases, ie, overflowed double numbers with long.MAX_VALUE. 
Introduce more conditional comparison for double and long numbers.
> Fix: comparing double with long 

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/EmulatorCredentials.java
`EmulatorCredentials` extends the abstract `Credentials` class. The signature of `getAuthenticationType()` function of this class does not indicate that this API could throw, and based on [this description](https://cloud.google.com/java/docs/reference/google-auth-library/latest/com.google.auth.oauth2.OAuth2Credentials#com_google_auth_oauth2_OAuth2Credentials_getAuthenticationType__), I don't think it should.
Fixes #2002.
> fix: getAuthenticationType in EmulatorCredentials should not throw.

- README.md
- google-cloud-firestore/pom.xml
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITE2ETracingTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITTracingTest.java
Update to use `io.opentelemetry.semconv:opentelemetry-semconv` (was io.opentelemetry:opentelemetry-semconv`). This version will be managed by shared-deps.
> deps: Migrate to io.opentelemetry.semconv:opentelemetry-semconv dep

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreException.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreExceptionTest.java
While creating a FirestoeException from an ApiException, it does not set `status` property, which is required by client side metrics feature. 
To be able to correctly collect an operation status(OK, DEADLINE_EXCEEDED,ABORTED...) instead of defaulting it to UNKNOWN, this PR maps StatusCode to Status, based on the 1:1 mapping relationship between enum `StatusCode.Code` and `Status.Code`, while creating FirestoreException from an ApiException.
> Fix: Status is missing while creating FirestoreException from ApiException

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Order.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/OrderTest.java
This PR both improves performance and simplifies the UTF-8 string comparison logic. It addresses prior performance regressions by introducing a more optimized algorithm for string ordering.
The semantics of the UTF-8 string comparison logic were originally fixed by #1967, but this fix caused a material performance degradation, which was then improved by #2021. The performance was, however, presumably still sub-optimal, and this PR further improves the speed back to close to its original speed and, serendipitously, simplifies the algorithm too.
This PR effectively ports the following two PRs from the firebase-android-sdk repository:
- https://github.com/firebase/firebase-android-sdk/pull/7098
- https://github.com/firebase/firebase-android-sdk/pull/7109
* **Performance Optimization**: The …
> fix: Further improve performance of the UTF-8 string comparison logic

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
Should fix: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3933
> fix: Implement BulkWriter shutdown logic
