googleapis/java-firestore

- google-cloud-firestore/pom.xml
- grpc-google-cloud-firestore-admin-v1/pom.xml
- grpc-google-cloud-firestore-v1/pom.xml
- grpc-google-cloud-firestore-v1beta1/pom.xml
- pom.xml
- proto-google-cloud-firestore-admin-v1/pom.xml
- proto-google-cloud-firestore-v1/pom.xml
- proto-google-cloud-firestore-v1beta1/pom.xml
Fixes dependency build failures in #7
> build: add undeclared dependencies to poms

- google-cloud-firestore-bom/pom.xml
- google-cloud-firestore/pom.xml
- grpc-google-cloud-firestore-admin-v1/pom.xml
- grpc-google-cloud-firestore-v1/pom.xml
- grpc-google-cloud-firestore-v1beta1/pom.xml
- pom.xml
- proto-google-cloud-firestore-admin-v1/pom.xml
- proto-google-cloud-firestore-v1/pom.xml
- proto-google-cloud-firestore-v1beta1/pom.xml
- versions.txt
add versions for google-cloud-firestore-parent and google-cloud-firestore-bom to versions.txt
> build: update version number of google-cloud-firestore-parent to be consistent with google-cloud-firestore

- google-cloud-firestore-bom/pom.xml
> fix: add google-cloud-firestore to bom

- google-cloud-firestore/pom.xml
- grpc-google-cloud-firestore-admin-v1/pom.xml
- grpc-google-cloud-firestore-v1/pom.xml
- grpc-google-cloud-firestore-v1beta1/pom.xml
> fix: remove error_prone_annotations exclusion rules from poms

- pom.xml
> revert: deps: update opencensus.version to v0.25.0 (#105)

- .kokoro/nightly/integration.cfg
- synth.py
> build: configure nightly integration tests to use the correct project

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/WatchTest.java
> chore: remove unused throws from test methods

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOptions.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/RateLimiter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/WriteResult.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
Porting from node (multiple commits).
TODO:
- Add POJO support.
> fix: Add BulkWriter

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/1117).
Will add integration tests in separate PR.
> fix: use sentinel on BulkWriter.delete()

- google-cloud-firestore/pom.xml
- grpc-google-cloud-firestore-admin-v1/pom.xml
- grpc-google-cloud-firestore-v1/pom.xml
- grpc-google-cloud-firestore-v1beta1/pom.xml
- pom.xml
- proto-google-cloud-firestore-admin-v1/pom.xml
- proto-google-cloud-firestore-v1/pom.xml
- proto-google-cloud-firestore-v1beta1/pom.xml
> feat(deps): adopt flatten plugin and google-cloud-shared-dependencies

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Internal.java
> fix: expose FirestoreImpl.autoId() for use in frameworks

- samples/snippets/pom.xml
copied from original implementation in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1523
> fix(samples): re-add maven exec config for Quickstart sample

- synth.py
Fixes https://github.com/googleapis/java-firestore/issues/371
> chore: exclude Bundle Proto from Synthtool run

- samples/snippets/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
- samples/snippets/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
Port of nodejs samples added in https://github.com/firebase/snippets-node/pull/156
Samples build won't pass until next release of cloud bom and libraries bom
> samples: add new samples for != and NOT IN queries

- .repo-metadata.json
> chore: add @googleapis/api-firestore to codeowner_team

- LICENSE
The local tooling doesn't recognize this repo as Apache-2.0 for some reason.  Trying to investigate.
> chore: update LICENSE formatting

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriterOperation.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
- lastOperation is read from multiple threads
- the rate limiter is not thread-safe
> chore: fix some potential threading issues in BulkWriter

- samples/snippets/src/main/java/com/example/firestore/Quickstart.java
> chore: modify sample region tag to more closely match others

- samples/snippets/src/main/java/com/example/firestore/Quickstart.java
Cleaning up some old region tags.
> chore(samples): remove old region tags

- google-cloud-firestore/pom.xml
> deps: update google-cloud-conformance-tests to 0.2.0

- pom.xml
> chore: cleanup cloud rad gen profile

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Add a test to cover the a successful transaction with readTime set before the last time changing the document.
> tests: add coverage for a successful read-only transaction with readTime

- samples/native-image-sample/pom.xml
> docs(sample): remove unused native-image-support module

- .kokoro/build.sh
- .kokoro/presubmit/graalvm-native-17.cfg
- README.md
- owlbot.py
> fix: add build script for JDK 17 native image testing

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
> perf: Change how proto was called in Query.java

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/RateLimiter.java
Fixes https://github.com/googleapis/java-firestore/issues/998
> chore: fixing firestore ramping_up_traffic links

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuerySnapshot.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
The wording is (mostly) copied from https://github.com/firebase/firebase-android-sdk/pull/4143
> docs: Write javadocs for COUNT API

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITQueryCountTest.java
Googlers see b/246425475 for details.
> test: Add invalid collection name in a COUNT query integration test

- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> chore: update native image checks to use graalvm 22.3.0

- google-cloud-firestore-bom/pom.xml
- pom.xml
- samples/native-image-sample/pom.xml
This PR combines the following PRs generated by renovate-bot into a single PR:
* https://github.com/googleapis/java-firestore/pull/1138
* https://github.com/googleapis/java-firestore/pull/1140
* https://github.com/googleapis/java-firestore/pull/1141
* https://github.com/googleapis/java-firestore/pull/1142
> deps: update multiple dependencies atomically

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/annotation/DocumentId.java
Updating comments to remove javadoc lint errors.
> Fix javadoc lint errors

- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> chore: update graalvm container images to 22.3.3

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateField.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/AggregateQuery.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentChange.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
> docs: Remove latin abbreviations from comments.

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/QuerySnapshot.java
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> refactor: Optimize arraylist instanciation.

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
Apply the feedback to the count and aggregation API documentation as suggested in https://github.com/firebase/firebase-js-sdk/pull/6608. This is a port of https://github.com/firebase/firebase-js-sdk/pull/7933.
> docs: tweak Count API docs

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
The burden of handling duplicate `onComplete` signals should be on `internalStream`, and not on all the callers that use it.
currently `get()` and `stream()` APIs call the underlying `internalStream`, and each of them are implementing the same logic to avoid duplicate completions. This should be handled at the lower (internalStream) function. Also, future callers of `internalStream` may not realize they need to implement this logic.
> fix: `internalStream` should handle duplicate `onComplete`s.

- .github/workflows/unmanaged-dependency-check.yaml
Please refer to internal ticket: b/320677266
> chore: add an unmanaged dependency check

- renovate.json
> chore: add renovate-bot config to update sdk-platform-java-config

- README.md
- google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
Add support for `java.time.Instant` as a time type.
Fixes #509☕️
> feat: `Instant` support

- .github/workflows/unmanaged-dependency-check.yaml
- renovate.json
In this PR:
- Change renovate config to update java shared config with unmanaged dependency check together.
> chore: update renovate for unmanaged dependency check

- google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
CI sometimes fails on `listenToDocumentsWithVectors`, and as best as I can tell, it is because of race condition in test.
There is a blocking call on listener that precedes incrementing semaphore that controls switch statement. Consequently, the case that deletes the document runs twice. The second time, the document has been deleted, so assertion fails on `assertNotNull(docSnap)` line 1456. This can happen if the executor on listener is a thread pool capable of concurrent execution, allowing next snapshot to process, before previous snapshot is done processing.
This PR makes the code more readable, and removes any chance of race condition.
I have applied this to both places where this pattern appears.
> fix: Remove race condition in test.

- renovate.json
In this PR:
- Update renovate to manage action from sdk-platform-java
- Group dependency updates from sdk-platform-java in one PR.
> chore: setup renovate to update action

- google-cloud-firestore/src/main/java/com/google/cloud/firestore/BulkWriter.java
- google-cloud-firestore/src/test/java/com/google/cloud/firestore/BulkWriterTest.java
> fix: Resolve RejectedExecutionException that occurred on BulkWriter close or executor shutdown
